[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP.git#812ed5e
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
build_flags =
  -DMINIMP3_IMPLEMENTATION
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
board_build.filesystem = spiffs

monitor_speed = 115200